/**
 * In-memory demo store for ClerkOS — Alpha Crown Court.
 * Used automatically when DATABASE_URL is not set.
 * All exported arrays are mutable so mutations persist for the server's lifetime.
 */

import type {
  Case,
  ClerkAllocation,
  ClerkDiary,
  Document,
  Hearing,
  Tenant,
  User,
} from '../drizzle/schema';

export const MOCK_TENANT_ID = 'aaaaaaaa-0000-0000-0000-000000000001';

function daysFromToday(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() + n);
  return d.toISOString().slice(0, 10);
}

export const mockTenant: Tenant = {
  id: MOCK_TENANT_ID,
  name: 'Alpha Crown Court',
  slug: 'alpha',
  plan: 'professional',
  settings: {
    timezone: 'Europe/London',
    dateFormat: 'DD/MM/YYYY',
    caseNumberPrefix: 'ACC',
  },
  createdAt: new Date('2024-01-01'),
  updatedAt: new Date('2024-01-01'),
};

export const mockUsers: User[] = [
  {
    id: 1,
    tenantId: MOCK_TENANT_ID,
    openId: 'admin-user',
    name: 'Patricia Chen',
    email: 'patricia.chen@alphacrown.court.gov.uk',
    loginMethod: 'dev',
    role: 'admin (senior clerk / manager)',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
    lastSignedIn: new Date(),
  },
  {
    id: 2,
    tenantId: MOCK_TENANT_ID,
    openId: 'clerk-user',
    name: 'James Okafor',
    email: 'james.okafor@alphacrown.court.gov.uk',
    loginMethod: 'dev',
    role: 'standard clerk',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date(),
    lastSignedIn: new Date(),
  },
];

export let mockCases: Case[] = [
  {
    id: 1,
    tenantId: MOCK_TENANT_ID,
    referenceNumber: 'ACC-2024-001',
    title: 'R v Thompson — Aggravated Assault',
    status: 'in_progress',
    caseType: 'Criminal',
    plaintiff: 'Crown Prosecution Service',
    defendant: 'Daniel Thompson',
    judge: 'HHJ Margaret Blackwell',
    description: 'Section 20 GBH. Incident 14 March 2024. Multiple witnesses identified.',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 2,
    tenantId: MOCK_TENANT_ID,
    referenceNumber: 'ACC-2024-002',
    title: 'Hadley v Baxendale Logistics Ltd',
    status: 'open',
    caseType: 'Civil',
    plaintiff: 'Sarah Hadley',
    defendant: 'Baxendale Logistics Ltd',
    judge: 'HHJ Peter Saunders',
    description: 'Breach of contract. Consequential loss claim £142,000.',
    createdAt: new Date('2024-03-15'),
    updatedAt: new Date('2024-03-15'),
  },
  {
    id: 3,
    tenantId: MOCK_TENANT_ID,
    referenceNumber: 'ACC-2024-003',
    title: 'Re: Harrison Estate — Probate Dispute',
    status: 'on_hold',
    caseType: 'Probate',
    plaintiff: 'Emily Harrison',
    defendant: 'Robert Harrison',
    judge: 'HHJ Margaret Blackwell',
    description: 'Contested will. Estate value £890,000. Awaiting expert valuation.',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: 4,
    tenantId: MOCK_TENANT_ID,
    referenceNumber: 'ACC-2023-078',
    title: 'R v Patel — Fraud by Representation',
    status: 'closed',
    caseType: 'Criminal',
    plaintiff: 'Crown Prosecution Service',
    defendant: 'Amir Patel',
    judge: 'HHJ James Worthington',
    description: 'Identity fraud. Guilty plea entered. Sentenced 18 months suspended.',
    createdAt: new Date('2023-09-01'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: 5,
    tenantId: MOCK_TENANT_ID,
    referenceNumber: 'ACC-2024-004',
    title: 'Meridian Tech v ClearData Solutions',
    status: 'open',
    caseType: 'Commercial',
    plaintiff: 'Meridian Tech Ltd',
    defendant: 'ClearData Solutions Ltd',
    judge: null,
    description: 'IP infringement. Software licensing dispute. Interim injunction sought.',
    createdAt: new Date('2024-04-18'),
    updatedAt: new Date('2024-04-18'),
  },
];

export let mockHearings: Hearing[] = [
  {
    id: 1,
    tenantId: MOCK_TENANT_ID,
    caseId: 1,
    hearingDate: daysFromToday(0),
    hearingTime: '09:30',
    courtroom: 'Court 3',
    judge: 'HHJ Margaret Blackwell',
    status: 'scheduled',
    notes: 'Prosecution opening statement. Estimated 3 hours.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    tenantId: MOCK_TENANT_ID,
    caseId: 2,
    hearingDate: daysFromToday(0),
    hearingTime: '14:00',
    courtroom: 'Court 1',
    judge: 'HHJ Peter Saunders',
    status: 'scheduled',
    notes: 'Case management conference. Directions expected.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    tenantId: MOCK_TENANT_ID,
    caseId: 3,
    hearingDate: daysFromToday(1),
    hearingTime: '10:00',
    courtroom: 'Court 2',
    judge: 'HHJ Margaret Blackwell',
    status: 'scheduled',
    notes: 'Interim application. Permission to appoint independent expert.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    tenantId: MOCK_TENANT_ID,
    caseId: 1,
    hearingDate: daysFromToday(7),
    hearingTime: '09:30',
    courtroom: 'Court 3',
    judge: 'HHJ Margaret Blackwell',
    status: 'scheduled',
    notes: 'Defence opening statement and first witness.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 5,
    tenantId: MOCK_TENANT_ID,
    caseId: 4,
    hearingDate: daysFromToday(-7),
    hearingTime: '10:30',
    courtroom: 'Court 1',
    judge: 'HHJ James Worthington',
    status: 'completed',
    notes: 'Sentencing hearing. Suspended sentence imposed.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 6,
    tenantId: MOCK_TENANT_ID,
    caseId: 3,
    hearingDate: daysFromToday(-14),
    hearingTime: '14:00',
    courtroom: 'Court 2',
    judge: 'HHJ Margaret Blackwell',
    status: 'postponed',
    notes: 'Postponed — expert witness unavailable. Rescheduled.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export let mockDocuments: Document[] = [
  {
    id: 1,
    tenantId: MOCK_TENANT_ID,
    caseId: 1,
    fileName: 'prosecution-opening-brief.pdf',
    blobPath: null,
    fileUrl: '/demo/docs/1',
    fileType: 'application/pdf',
    fileSize: 245760,
    documentType: 'Opening Brief',
    version: 1,
    contentHash: 'abc123def456abc123def456abc123def456abc123def456abc123def456abc1',
    approvedForBundle: 1,
    uploadedBy: 1,
    createdAt: new Date('2024-04-01'),
    updatedAt: new Date('2024-04-01'),
  },
  {
    id: 2,
    tenantId: MOCK_TENANT_ID,
    caseId: 1,
    fileName: 'witness-statement-chen.pdf',
    blobPath: null,
    fileUrl: '/demo/docs/2',
    fileType: 'application/pdf',
    fileSize: 102400,
    documentType: 'Witness Statement',
    version: 1,
    contentHash: 'def456abc789def456abc789def456abc789def456abc789def456abc789def4',
    approvedForBundle: 1,
    uploadedBy: 2,
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
  },
  {
    id: 3,
    tenantId: MOCK_TENANT_ID,
    caseId: 1,
    fileName: 'cctv-footage-exhibit-A.mp4',
    blobPath: null,
    fileUrl: '/demo/docs/3',
    fileType: 'video/mp4',
    fileSize: 52428800,
    documentType: 'Exhibit',
    version: 1,
    contentHash: null,
    approvedForBundle: 0,
    uploadedBy: 2,
    createdAt: new Date('2024-04-08'),
    updatedAt: new Date('2024-04-08'),
  },
  {
    id: 4,
    tenantId: MOCK_TENANT_ID,
    caseId: 2,
    fileName: 'contract-2023-baxendale.pdf',
    blobPath: null,
    fileUrl: '/demo/docs/4',
    fileType: 'application/pdf',
    fileSize: 512000,
    documentType: 'Contract',
    version: 1,
    contentHash: 'aaa111bbb222aaa111bbb222aaa111bbb222aaa111bbb222aaa111bbb222aaa1',
    approvedForBundle: 1,
    uploadedBy: 1,
    createdAt: new Date('2024-03-16'),
    updatedAt: new Date('2024-03-16'),
  },
  {
    id: 5,
    tenantId: MOCK_TENANT_ID,
    caseId: 2,
    fileName: 'loss-calculation-report.xlsx',
    blobPath: null,
    fileUrl: '/demo/docs/5',
    fileType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    fileSize: 84992,
    documentType: 'Financial Report',
    version: 2,
    contentHash: 'ccc333ddd444ccc333ddd444ccc333ddd444ccc333ddd444ccc333ddd444ccc3',
    approvedForBundle: 0,
    uploadedBy: 1,
    createdAt: new Date('2024-03-20'),
    updatedAt: new Date('2024-04-10'),
  },
  {
    id: 6,
    tenantId: MOCK_TENANT_ID,
    caseId: 3,
    fileName: 'harrison-will-original.pdf',
    blobPath: null,
    fileUrl: '/demo/docs/6',
    fileType: 'application/pdf',
    fileSize: 163840,
    documentType: 'Will Document',
    version: 1,
    contentHash: 'eee555fff666eee555fff666eee555fff666eee555fff666eee555fff666eee5',
    approvedForBundle: 1,
    uploadedBy: 1,
    createdAt: new Date('2024-02-12'),
    updatedAt: new Date('2024-02-12'),
  },
  {
    id: 7,
    tenantId: MOCK_TENANT_ID,
    caseId: 3,
    fileName: 'property-valuation-draft.pdf',
    blobPath: null,
    fileUrl: '/demo/docs/7',
    fileType: 'application/pdf',
    fileSize: 409600,
    documentType: 'Expert Report',
    version: 1,
    contentHash: null,
    approvedForBundle: 0,
    uploadedBy: 2,
    createdAt: new Date('2024-04-02'),
    updatedAt: new Date('2024-04-02'),
  },
  {
    id: 8,
    tenantId: MOCK_TENANT_ID,
    caseId: 5,
    fileName: 'software-licence-agreement.pdf',
    blobPath: null,
    fileUrl: '/demo/docs/8',
    fileType: 'application/pdf',
    fileSize: 819200,
    documentType: 'Licence Agreement',
    version: 1,
    contentHash: 'ggg777hhh888ggg777hhh888ggg777hhh888ggg777hhh888ggg777hhh888ggg7',
    approvedForBundle: 0,
    uploadedBy: 1,
    createdAt: new Date('2024-04-19'),
    updatedAt: new Date('2024-04-19'),
  },
];

export let mockAllocations: ClerkAllocation[] = [
  {
    id: 1,
    tenantId: MOCK_TENANT_ID,
    clerkId: 2,
    caseId: 1,
    taskType: 'Bundle Preparation',
    priority: 'urgent',
    status: 'in_progress',
    dueDate: daysFromToday(1),
    notes: 'Prepare trial bundle for opening statement hearing.',
    assignedAt: new Date('2024-04-15'),
    completedAt: null,
    createdAt: new Date('2024-04-15'),
    updatedAt: new Date(),
  },
  {
    id: 2,
    tenantId: MOCK_TENANT_ID,
    clerkId: 2,
    caseId: 2,
    taskType: 'Document Filing',
    priority: 'high',
    status: 'pending',
    dueDate: daysFromToday(3),
    notes: 'File claimant witness statements with court registry.',
    assignedAt: new Date('2024-04-18'),
    completedAt: null,
    createdAt: new Date('2024-04-18'),
    updatedAt: new Date(),
  },
  {
    id: 3,
    tenantId: MOCK_TENANT_ID,
    clerkId: 1,
    caseId: 3,
    taskType: 'Expert Instruction Letter',
    priority: 'medium',
    status: 'pending',
    dueDate: daysFromToday(10),
    notes: 'Draft letter to appointed expert setting out scope of valuation.',
    assignedAt: new Date('2024-04-20'),
    completedAt: null,
    createdAt: new Date('2024-04-20'),
    updatedAt: new Date(),
  },
  {
    id: 4,
    tenantId: MOCK_TENANT_ID,
    clerkId: 2,
    caseId: 4,
    taskType: 'Case Closure',
    priority: 'low',
    status: 'completed',
    dueDate: daysFromToday(-5),
    notes: 'Archive all case documents and update registry.',
    assignedAt: new Date('2024-01-22'),
    completedAt: new Date('2024-01-25'),
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-25'),
  },
];

export let mockDiaries: ClerkDiary[] = [
  {
    id: 1,
    tenantId: MOCK_TENANT_ID,
    clerkId: 1,
    date: daysFromToday(0),
    hearingId: 1,
    allocationId: null,
    notes: 'Attend R v Thompson opening. Liaise with prosecution counsel re: exhibits.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    tenantId: MOCK_TENANT_ID,
    clerkId: 1,
    date: daysFromToday(0),
    hearingId: 2,
    allocationId: null,
    notes: 'Case management conference — Hadley. Take directions note.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    tenantId: MOCK_TENANT_ID,
    clerkId: 2,
    date: daysFromToday(1),
    hearingId: 3,
    allocationId: 1,
    notes: 'Harrison interim application. Bundle due today — confirm with senior clerk.',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export function nextMockId(arr: Array<{ id: number }>): number {
  return arr.reduce((max, item) => Math.max(max, item.id), 0) + 1;
}
