export interface ExampleCommand {
  text: string;
  action: string;
  expected?: Record<string, unknown>;
}

export const groupedExamples: Record<string, ExampleCommand[]> = {
  reminders: [
    { text: 'Remind me to review the FineGuard report tomorrow at 9am', action: 'create_reminder' },
    { text: 'Set a reminder for the board meeting on Friday at 3pm', action: 'create_reminder' },
    { text: 'Remind Dagon to file the accounts next Monday', action: 'create_reminder' },
    { text: 'Remind the team about the deadline on 2026-08-15 at 5pm', action: 'create_reminder' },
    { text: 'Create a reminder to call the client about the invoice', action: 'create_reminder' },
    { text: 'Remind me to submit the quarterly report by end of day', action: 'create_reminder' },
    { text: 'Set a reminder for the meeting with the auditors next week', action: 'create_reminder' },
    { text: 'Remind me to pay the supplier invoice on Friday', action: 'create_reminder' },
    { text: 'Schedule a reminder to renew the domain name', action: 'create_reminder' },
    { text: 'Remind me to follow up with the client on Monday', action: 'create_reminder' },
    { text: 'Set a reminder to cancel the subscription before trial ends', action: 'create_reminder' },
    { text: 'Remind the team to prepare the presentation', action: 'create_reminder' },
    { text: 'Remind me to check the server logs at 4pm', action: 'create_reminder' },
    { text: 'Create a reminder for the compliance review next month', action: 'create_reminder' },
    { text: 'Remind me to update the password for the admin panel', action: 'create_reminder' },
    { text: 'Set a reminder to archive old projects', action: 'create_reminder' },
    { text: 'Remind me to order new business cards', action: 'create_reminder' },
    { text: 'Create a reminder to schedule the annual performance reviews', action: 'create_reminder' },
    { text: 'Remind me to check the bank balance tomorrow morning', action: 'create_reminder' },
    { text: 'Set a reminder for the investor call next Thursday', action: 'create_reminder' },
  ],
  tasks: [
    { text: 'Create a task to update the client contract', action: 'create_task' },
    { text: 'Add a task: prepare quarterly financials', action: 'create_task' },
    { text: 'Task: design the new UI mockups', action: 'create_task' },
    { text: 'Todo: write the project report', action: 'create_task' },
    { text: 'Add task to fix the bug in the parser', action: 'create_task' },
    { text: 'Create a task for onboarding the new hire', action: 'create_task' },
    { text: 'Task: review the pull request from the team', action: 'create_task' },
    { text: 'Add a task to conduct user interviews', action: 'create_task' },
    { text: 'Todo: update the API documentation', action: 'create_task' },
    { text: 'Create a task to clean up the database', action: 'create_task' },
    { text: 'Task: prepare the presentation for the board meeting', action: 'create_task' },
    { text: 'Add a task to optimize the image loading', action: 'create_task' },
    { text: 'Todo: write tests for the new feature', action: 'create_task' },
    { text: 'Create a task to deploy the staging environment', action: 'create_task' },
    { text: 'Task: review the security audit report', action: 'create_task' },
    { text: 'Add a task to migrate the legacy data', action: 'create_task' },
    { text: 'Create a task to update the company handbook', action: 'create_task' },
    { text: 'Todo: schedule the next sprint planning', action: 'create_task' },
    { text: 'Add a task to review the vendor contracts', action: 'create_task' },
    { text: 'Task: create a backup of the production database', action: 'create_task' },
  ],
  meetings: [
    { text: 'Schedule a meeting with Chris and Dagon tomorrow at 11am about FineGuard', action: 'schedule_meeting' },
    { text: 'Arrange a sync with Michelle next Tuesday at 2pm', action: 'schedule_meeting' },
    { text: 'Set up a meeting with the board regarding the budget', action: 'schedule_meeting' },
    { text: 'Meeting with the marketing team on Wednesday at 10am', action: 'schedule_meeting' },
    { text: 'Sync with engineering about the new release', action: 'schedule_meeting' },
    { text: 'Schedule a call with the investors for Friday', action: 'schedule_meeting' },
    { text: 'Arrange a planning session for the next sprint', action: 'schedule_meeting' },
    { text: 'Set up a meeting with the compliance officer', action: 'schedule_meeting' },
    { text: 'Book a meeting room for the design review', action: 'schedule_meeting' },
    { text: 'Meeting with the customer success team at 3pm', action: 'schedule_meeting' },
    { text: 'Sync with the CEO about the strategy', action: 'schedule_meeting' },
    { text: 'Schedule a demo for the client next week', action: 'schedule_meeting' },
    { text: 'Arrange a retrospective for the last sprint', action: 'schedule_meeting' },
    { text: 'Set up a meeting with the external auditors', action: 'schedule_meeting' },
    { text: 'Book a meeting to discuss the product roadmap', action: 'schedule_meeting' },
    { text: 'Meeting with the legal team regarding the contract', action: 'schedule_meeting' },
    { text: 'Schedule a brainstorming session for the new campaign', action: 'schedule_meeting' },
    { text: 'Arrange a one-on-one with the team lead', action: 'schedule_meeting' },
    { text: 'Set up a meeting to review the Q3 metrics', action: 'schedule_meeting' },
    { text: 'Book a call with the technical advisor', action: 'schedule_meeting' },
  ],
  callbacks: [
    { text: 'Book a callback with James about the new invoice', action: 'book_callback' },
    { text: 'Schedule a call with Sarah tomorrow at 4pm', action: 'book_callback' },
    { text: 'Arrange a callback with the client regarding the proposal', action: 'book_callback' },
    { text: 'Call John back on Friday morning', action: 'book_callback' },
    { text: 'Phone the supplier about the order', action: 'book_callback' },
    { text: 'Book a callback with the support team for technical issues', action: 'book_callback' },
    { text: 'Schedule a call with the account manager', action: 'book_callback' },
    { text: 'Arrange a callback for the payment dispute', action: 'book_callback' },
    { text: 'Call the IT helpdesk about the system outage', action: 'book_callback' },
    { text: 'Phone the delivery company about the package', action: 'book_callback' },
    { text: 'Book a call with the freelance designer', action: 'book_callback' },
    { text: 'Schedule a call with the recruiter', action: 'book_callback' },
    { text: 'Arrange a callback from the billing department', action: 'book_callback' },
    { text: 'Call the courier to track the shipment', action: 'book_callback' },
    { text: 'Phone the hotel to confirm the booking', action: 'book_callback' },
    { text: 'Book a call with the business advisor', action: 'book_callback' },
    { text: 'Schedule a call with the tech support', action: 'book_callback' },
    { text: 'Arrange a callback about the warranty claim', action: 'book_callback' },
    { text: 'Call the bank about the loan application', action: 'book_callback' },
    { text: 'Phone the landlord about the lease renewal', action: 'book_callback' },
  ],
  email: [
    { text: 'Draft an email to support@firm.co.uk about the overdue payment', action: 'draft_email' },
    { text: 'Compose an email to the client with the updated contract', action: 'draft_email' },
    { text: 'Write a follow-up email to the team about the meeting', action: 'draft_email' },
    { text: 'Email the report to finance@company.com', action: 'draft_email' },
    { text: 'Draft a response to the complaint email', action: 'draft_email' },
    { text: 'Write an email to the vendor requesting a quote', action: 'draft_email' },
    { text: 'Send a reminder email about the upcoming deadline', action: 'draft_email' },
    { text: 'Draft a thank-you email to the interview candidates', action: 'draft_email' },
    { text: 'Compose a newsletter for the subscribers', action: 'draft_email' },
    { text: 'Email the sales team about the new leads', action: 'draft_email' },
    { text: 'Write a formal letter of resignation', action: 'draft_email' },
    { text: 'Draft an email to the press for the product launch', action: 'draft_email' },
    { text: 'Send a meeting minutes summary to all attendees', action: 'draft_email' },
    { text: 'Compose a referral request email', action: 'draft_email' },
    { text: 'Write a confirmation email for the order', action: 'draft_email' },
    { text: 'Draft a proposal email for the new project', action: 'draft_email' },
    { text: 'Email the HR about the job posting', action: 'draft_email' },
    { text: 'Write an apology email for the service interruption', action: 'draft_email' },
    { text: 'Draft a congratulatory email to the winning bidder', action: 'draft_email' },
    { text: 'Compose a status update email to stakeholders', action: 'draft_email' },
  ],
  invoices: [
    { text: 'Create an invoice for Bright Futures Consulting Ltd', action: 'create_invoice' },
    { text: 'Generate invoice for Acme Corp for $5,000', action: 'create_invoice' },
    { text: 'Bill GreenLeaf Catering for the services rendered', action: 'create_invoice' },
    { text: 'Send invoice to Northern Properties for rent', action: 'create_invoice' },
    { text: 'Invoice the client for the consulting work', action: 'create_invoice' },
    { text: 'Create an invoice for the software license renewal', action: 'create_invoice' },
    { text: 'Generate an invoice for the maintenance contract', action: 'create_invoice' },
    { text: 'Bill the tenant for the utilities', action: 'create_invoice' },
    { text: 'Send an invoice for the advertising services', action: 'create_invoice' },
    { text: 'Invoice the partner for the joint project', action: 'create_invoice' },
    { text: 'Create an invoice for the training session', action: 'create_invoice' },
    { text: 'Generate a proforma invoice for the order', action: 'create_invoice' },
    { text: 'Bill the client for the milestone payment', action: 'create_invoice' },
    { text: 'Send an invoice for the legal consultation', action: 'create_invoice' },
    { text: 'Invoice the customer for the product shipment', action: 'create_invoice' },
    { text: 'Create an invoice for the annual subscription', action: 'create_invoice' },
    { text: 'Generate an invoice for the consulting hours', action: 'create_invoice' },
    { text: 'Bill the subcontractor for the work done', action: 'create_invoice' },
    { text: 'Send a revised invoice to the client', action: 'create_invoice' },
    { text: 'Create a credit note for the returned goods', action: 'create_invoice' },
  ],
  unknown: [
    { text: 'What is the weather today?', action: 'unknown' },
    { text: 'How many users are online?', action: 'unknown' },
    { text: 'Tell me a joke', action: 'unknown' },
    { text: 'Translate this to French', action: 'unknown' },
    { text: 'What is the capital of France?', action: 'unknown' },
    { text: 'Play some music', action: 'unknown' },
    { text: 'Show me the latest news', action: 'unknown' },
    { text: 'What is the stock price of AAPL?', action: 'unknown' },
    { text: 'Define "machine learning"', action: 'unknown' },
    { text: 'Who won the football match?', action: 'unknown' },
    { text: 'List all the files in the current directory', action: 'unknown' },
    { text: 'Tell me a fun fact about dogs', action: 'unknown' },
    { text: 'What is the meaning of life?', action: 'unknown' },
    { text: 'Can you book a flight?', action: 'unknown' },
    { text: 'Order a pizza', action: 'unknown' },
    { text: 'What time is it?', action: 'unknown' },
  ],
};

export const allExamples = Object.values(groupedExamples).flat();
